name: MetatechCRM
description: "MetaTechCRM"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-172.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  fl_chart: ^1.0.0
  gap: ^3.0.1
  auto_size_text: ^3.0.0
  firebase_core: ^3.14.0
  flutter_side_menu: ^0.5.41
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/logo/
   - assets/font/Poppins-Regular.ttf
   - assets/font/Poppins-Medium.ttf
   - assets/font/Poppins-SemiBold.ttf
   - assets/font/Poppins-Bold.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700